// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID           pgtype.UUID
	Name         string
	Cnpj         string
	ContactEmail pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type CompanyDriverBinding struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	DriverID  pgtype.UUID
	StartDate pgtype.Date
	EndDate   pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Payment struct {
	ID        pgtype.UUID
	TripID    pgtype.UUID
	DriverID  pgtype.UUID
	Amount    pgtype.Numeric
	Status    string
	PaidAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Trip struct {
	ID              pgtype.UUID
	DriverID        pgtype.UUID
	CompanyID       pgtype.UUID
	StartTime       pgtype.Timestamptz
	EndTime         pgtype.Timestamptz
	TravelledMeters pgtype.Int4
	StartPhotoUrl   pgtype.Text
	EndPhotoUrl     pgtype.Text
	CreatedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type TripLocation struct {
	ID        pgtype.UUID
	TripID    pgtype.UUID
	Lat       float64
	Lng       float64
	Timestamp pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TripPhotoMetadatum struct {
	ID          pgtype.UUID
	TripID      pgtype.UUID
	Type        string
	TakenAt     pgtype.Timestamptz
	Lat         pgtype.Float8
	Lng         pgtype.Float8
	DeviceModel pgtype.Text
	Orientation pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
