name: Deploy to Cloud Run

on:
  push:
    branches: ["**"]

env:
  SERVICE: PubliCar
  DOCKERHUB_USERNAME: paulooo
  IMAGE_NAME: publicar-backend

jobs:
  sqlc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Download dependencies
        run: go mod download

      - name: Run database migrations first
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/db/migrations:/migrations \
            migrate/migrate \
            -path=/migrations \
            -database "${{ secrets.DB_URL }}" \
            up

      - name: Generate SQLC code using Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src sqlc/sqlc:1.29.0 generate -f db/sqlc.yml

      - name: Check for uncommitted changes
        run: |
          git diff --exit-code || (echo "sqlc generated code is out of sync" && exit 1)

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push images
        run: |
          SHA_TAG=${{ steps.vars.outputs.sha_short }}
          DH_IMAGE=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          GCR_IMAGE=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}

          docker build -t $DH_IMAGE:$SHA_TAG -t $DH_IMAGE:latest .
          docker push $DH_IMAGE:$SHA_TAG
          docker push $DH_IMAGE:latest
